version: '2'
services:
  postgres.dev:
    build:
     context: ../../containers/postgres
     args:
      - DDL_URL=${DDL_URL}
    image: hdp/postgres
    networks:
     - dev
    hostname: postgres
    domainname: dev
  ambari-server.dev:
    build: 
      context: ../../containers/ambari-server
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
    image: hdp/ambari-server
    networks:
     - dev
    hostname: ambari-server
    domainname: dev
    ports:
     - "8080:8080"
  master0.dev:
    build:
      context: ../../containers/node
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
       - HDP_REPO_URL=${HDP_REPO_URL}
    image: hdp/master
    privileged: true
    networks:
     - dev
    hostname: master0
    domainname: dev
    ports:
     # ZooKeeper
     - "2181:2181"
     # HDFS
     - "8020:8020"
     - "9000:9000"
     - "50090:50090"
     # YARN
     - "8088:8088"
     - "8050:8050"
     - "8025:8025"
     - "8030:8030"
     - "8141:8141"
     - "45454:45454"
     - "10200:10200"
     - "8188:8188"
     - "8190:8190"
     - "19888:19888"
     # HiveServer2
     - "10000:10000"
     - "9999:9999"
     - "9933:9933"
     - "10015:10015"
     # HBase
     - "16000:16000"
     - "16010:16010"
     # Storm
     - "8000:8000"
     - "8744:8744"
     # Oozie
     - "11000:11000"
     - "11443:11443"
     # Knox
     - "8443:8443"
     # Ranger
     - "6080:6080"
     - "6182:6182"
     - "6083:6083"
     - "6183:6183"
     # Grafana
     - "3000:3000"
     # Zeppelin
     - "9995:9995"
     # Kerberos
     #- "88:88"
  dn0.dev:
    build:
      context: ../../containers/node
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
       - HDP_REPO_URL=${HDP_REPO_URL}
    image: hdp/worker
    privileged: true
    networks:
     - dev
    hostname: dn0
    domainname: dev
    ports:
     # HDFS
     - "50070:50070"
     - "50470:50470"
     - "50075:50075"
     - "50475:50475"
     - "50010:50010"
     - "50020:50020"
     - "50030:50030"
     # HBase
     - "16020:16020"
     - "16030:16030"
     # Yarn
     - "45455:45454"
     - "8042:8042"
     # Solr
     - "8983:8983"
     # Kafka
     - "6667:6667"
  dn1.dev:
    build:
      context: ../../containers/node
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
       - HDP_REPO_URL=${HDP_REPO_URL}
    image: hdp/worker
    privileged: true
    networks:
     - dev
    hostname: dn1
    domainname: dev
    ports:
     # HDFS
     - "50071:50070"
     - "50471:50470"
     - "50076:50075"
     - "50476:50475"
     - "50011:50010"
     - "50021:50020"
     - "50031:50030"
     # HBase
     - "16021:16020"
     - "16031:16030"
     # Yarn
     - "45451:45454"
     - "8041:8042"
     # Solr
     - "8984:8983"
     # Kafka
     - "6668:6667"
  dn2.dev:
    build:
      context: ../../containers/node
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
       - HDP_REPO_URL=${HDP_REPO_URL}
    image: hdp/worker
    privileged: true
    networks:
     - dev
    hostname: dn2
    domainname: dev
    ports:
     # HDFS
     - "50072:50070"
     - "50472:50470"
     - "50077:50075"
     - "50477:50475"
     - "50012:50010"
     - "50022:50020"
     - "50032:50030"
     # HBase
     - "16022:16020"
     - "16032:16030"
     # Yarn
     - "45452:45454"
     - "8043:8042"
     # Solr
     - "8985:8983"
     # Kafka
     - "6669:6667"
networks:
  dev:
    driver: bridge
